name: Bandit checks

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: python-bandit with code annotations
      uses: ./
      with:
        project_path: main.py
