# This is a basic workflow to help you get started with Actions

name: Bandit checks

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: python-bandit with code annotations
      uses: ./ # Uses an action in the root directory
      with:
        project_path: main.py
