name: Bandit checks

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: python-bandit with code annotations
      #uses: ioggstream/bandit-report-artifacts@v0.0.2
      uses: VCTLabs/bandit-report-artifacts@master
      with:
        project_path: main.py
